# Use an official Node.js runtime as a base image
FROM node:21 as development

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install Yarn
RUN command -v yarn >/dev/null 2>&1 || { npm install -g yarn; }

# Install application dependencies using Yarn
RUN npm install

# Expose the port that your app runs on
EXPOSE 8080

# Command for dev environment
CMD ["npm", "start"];