# Build stage
FROM node:20.17.0 AS build

WORKDIR /app

COPY package*.json ./

RUN yarn --network-timeout 1000000

COPY . .

RUN yarn run build

# Production stage
FROM node:20

WORKDIR /app

RUN yarn global add serve

COPY --from=build /app/build ./build
COPY --from=build /app/node_modules ./node_modules
COPY --from=build /app/package*.json ./

EXPOSE 80

CMD ["serve", "-s", "build", "-l", "tcp://0.0.0.0:80"]
