# Use an official Node.js runtime as a base image
FROM node:21

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install application dependencies using Yarn
RUN yarn --network-timeout 1000000

# Expose the port that your app runs on
EXPOSE 8080

# Command for dev environment
CMD ["yarn", "start"];