version: '3.8'

services:
  database:
    image: mysql:latest
    container_name: database-prod
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - tablecloth_db:/var/lib/mysql

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend-prod
    ports:
      - "8081:8081"
    volumes:
      - ./backend:/app:delegated
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    depends_on:
      - database

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: frontend-prod
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/app:delegated
    environment:
      - PORT=80
      - NODE_ENV=production
    env_file:
      - .env
    depends_on:
      - backend

volumes:
  tablecloth_db:
    external: true

x-project:
  name: tablecloth-prod