version: '3.8'

services:
  database:
    image: mysql:latest
    container_name: database
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8081:8081"
    volumes:
      - ./backend:/app:delegated  # Mount the local source code into the container
    environment:
      - NODE_ENV=development
    env_file:
      - .env
    depends_on:
      - database

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    volumes:
      - ./frontend:/app:delegated
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
    env_file:
      - .env
    depends_on:
      - backend

volumes:
  db:  # Define your named volume here
