version: '3.8'

services:
  database:
    image: mysql:8.2.0
    container_name: database
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - tablecloth_db:/var/lib/mysql

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: backend
    ports:
      - "8081:8081"
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    depends_on:
      - database

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: frontend
    ports:
      - "8080:80"
    environment:
      - PORT=80
      - NODE_ENV=production
      - VITE_BACKEND_HOST=http://tablecloth.local:8081
    env_file:
      - .env
    depends_on:
      - backend

  metabase:
    build:
      context: ./metabase
      dockerfile: Dockerfile
    container_name: metabase
    ports:
      - "3000:3000"
    environment:
      - MB_DB_FILE=/metabase-data/metabase.db
    volumes:
      - metabase-data-volume:/metabase-data

volumes:
  tablecloth_db:
    external: true
  metabase-data-volume:
    external: true

x-project:
  name: tablecloth-prod
