version: '3.8'

services:
  database:
    image: mysql:latest
    container_name: database
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8081:8081"
      - "9229:9229" 
    volumes:
      - ./backend:/app:delegated
    environment:
      - NODE_ENV=development
      - DEBUG_PORT=9229 
    env_file:
      - .env
    depends_on:
      - database

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: frontend-dev
    volumes:
      - ./frontend:/app:delegated
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
    env_file:
      - .env
    depends_on:
      - backend

volumes:
  db:
