version: '3'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8081:8081"  # Adjust the port as needed
    env_file:
      - .env
    depends_on:
      - database  # Assuming you have a database service

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "8080:8080"  # Adjust the port as needed
    env_file:
      - .env
    depends_on:
      - backend

  database:
    image: mysql:latest
    container_name: database
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql

volumes:
  db:  # Define your named volume here
