# Use an official Node.js runtime as a base image
FROM node:21

# Set the working directory in the container
WORKDIR /app

# Copy important files to the working directory
COPY package*.json ./
COPY yarn.lock ./
COPY wait.sh ./
COPY nodemon.json ./
COPY config ./config
COPY .sequelizerc ./

# Install Yarn and dos2unix
RUN apt-get update && apt-get install -y yarn dos2unix

# Convert line endings of wait.sh to LF
RUN dos2unix wait.sh

# Install dependencies using Yarn
RUN yarn --network-timeout 1000000

# Expose the port that your app runs on
EXPOSE 8081
EXPOSE 9229

# Command to run your application
CMD ["./wait.sh", "database", "3306", "--", "npx", "nodemon", "--trace-warnings", "--inspect=0.0.0.0:9229", "-L", "src/index.js"]